name: Jest Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jest-test-results
        path: coverage/  # Assuming you're generating test coverage reports
        retention-days: 30
