name: Jest Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: env  # If using GitHub environment to manage secrets
    env:
      SECRET: ${{ secrets.SECRET }}
      ISSUER_BASE_URL: ${{ secrets.ISSUER_BASE_URL }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      PORT: ${{ secrets.PORT }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      AUDIENCE: ${{ secrets.AUDIENCE }}
      AUTH_API_CLIENT_ID: ${{ secrets.AUTH_API_CLIENT_ID }}
      AUTH_API_SECRET: ${{ secrets.AUTH_API_SECRET }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      github-token: ${{ secrets.COVERALLS_REPO_TOKEN}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
            
